cluster.name: "docker-cluster"
network.host: 0.0.0.0

# For debug
# Search Slow log
# index.search.slowlog.threshold.query.warn: 10s
# index.search.slowlog.threshold.query.info: 5s
# index.search.slowlog.threshold.query.debug: 2s
# index.search.slowlog.threshold.query.trace: 500ms
#
# index.search.slowlog.threshold.fetch.warn: 1s
# index.search.slowlog.threshold.fetch.info: 800ms
# index.search.slowlog.threshold.fetch.debug: 500ms
# index.search.slowlog.threshold.fetch.trace: 200ms
#
# Index Slow log
# index.indexing.slowlog.threshold.index.warn: 10s
# index.indexing.slowlog.threshold.index.info: 5s
# index.indexing.slowlog.threshold.index.debug: 2s
# index.indexing.slowlog.threshold.index.trace: 500ms
# index.indexing.slowlog.level: info
# index.indexing.slowlog.source: 1000
# xpack.security.enabled: true
