server:
  port: 8080

app:
  elastic:
    connection-id: "__REMOTE__"
    server-name: "elasticsearch"
    port: 9200
    username: elastic
    password: changeme
    ca-path: "/Users/greeng/projects/eck-on-gke/es/certs/ca/ca.crt"
