server:
  port: 8080

app:
  elastic:
    connection-id: "__REMOTE__"
    server-name: "localhost"
    port: 9200
    username: elastic
    password: test123
    ca-path: "/Users/greeng/projects/eck-on-gke/es/certs/ca/ca.crt"
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false